### PR TITLE
hello-camkes-1: Hide soluton for idl4 file

### LINKED ISSUE #34: Solution code not hidden in --tut hello-camkes-1 gen
In `hello-camkes-1/interfaces/HelloSimple.idl4` Reading the hint, it seems that the following is expected

```c
/* Simple RPC interface */
procedure HelloSimple {
    /* TODO define RPC functions */
    /* hint 1: define at least one function that takes a string as input parameter. call it say_hello. no return value
     * hint 2: look at https://github.com/seL4/camkes-tool/blob/master/docs/index.md#creating-an-application
     */
};
```
got:
```c
/* Simple RPC interface */
procedure HelloSimple {
    /* TODO define RPC functions */
    /* hint 1: define at least one function that takes a string as input parameter. call it say_hello. no return value
     * hint 2: look at https://github.com/seL4/camkes-tool/blob/master/docs/index.md#creating-an-application
     */
    void say_hello(in string str);
};
```
If you go to `tutorials/hello-camkes-1.md`, line 177, you can see the filter-block with the line in question.
```c
/*- filter File("interfaces/HelloSimple.idl4") --*/
/* Simple RPC interface */
procedure HelloSimple {
/*-- filter TaskContent("hello", TaskContentType.BEFORE, subtask="interface") -*/
    /* TODO define RPC functions */
    /* hint 1: define at least one function that takes a string as input parameter. call it say_hello. no return value
     * hint 2: look at https://github.com/seL4/camkes-tool/blob/master/docs/index.md#creating-an-application
     */
/*-- endfilter -*/
/*-- filter TaskContent("hello", TaskContentType.COMPLETED, subtask="interface") -*/
    void say_hello(in string str);
/*-- endfilter -*/
};
/*-- endfilter -*/

```
This approach to filtering and generation is new to me. Not sure about what sort of changes might be needed, assuming this isn't working as intended.

### PR DESCRIPTION
**Pull request by kent-mcleod**
Fixes #34. Hide the solution for the idl4 definition part of the
tutorial at the start.

### CODE REVIEW

**Comment by kent-mcleod** [comment]
@ssrg-bamboo `test`

**Comment by nomadeel** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
