### PR TITLE
Fix rendering issues for dynamic-2

### LINKED ISSUE #39: dynamic-2 is misrendered on sel4.systems
- https://docs.sel4.systems/Tutorials/dynamic-2.html

It looks like the renderer has gotten confused about where code block fences start and end. It seems like it could be the fault of line 232 which has a closing fence with a leading space, but if not that then I have no idea.

### PR DESCRIPTION
**Pull request by nomadeel**
Fixes #39. Some of the `filter` and `set` statements had extra dashes at the end. Also fixed some of the code blocks so that they are not indented with the URL lists.

### CODE REVIEW

**Comment by nomadeel** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by nomadeel** [comment]
Rebased against master.

**Pull request merged**
