### PR TITLE
two critical letters reversed

### PR DESCRIPTION
**Pull request by laokz**

### CODE REVIEW

**Comment by nomadeel** [comment]
@ssrg-bamboo `test`

**Comment by nomadeel** [comment]
Thanks for fixing the typo!

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 7438f6111beea30736cdb69c814c34e764a33f0c

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - seL4-tutorials - EXT-laokz-master-44 | SUCCESSFUL |
| Code Quality - Style - seL4-tutorials - EXT-laokz-master-44 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - seL4-tutorials - EXT-laokz-master-44 | Style check on changed files | 1 of 3 jobs failed |

**Job: gitlint**
Build logs

    09-Mar-2020 10:07:01	Build Code Quality - Style - seL4-tutorials - EXT-laokz-master-44 - gitlint #1 (CQ-SEL4TUTORIALSSTYLE33-SEL4TUTORIALSGITLINTPR-1) started building on agent A local agent 1
    09-Mar-2020 10:07:01	I run on the Bamboo server!
    09-Mar-2020 10:07:01	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE33-SEL4TUTORIALSGITLINTPR
    09-Mar-2020 10:07:01	Executing build Code Quality - Style - seL4-tutorials - EXT-laokz-master-44 - gitlint #1 (CQ-SEL4TUTORIALSSTYLE33-SEL4TUTORIALSGITLINTPR-1)
    09-Mar-2020 10:07:01	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE33-SEL4TUTORIALSGITLINTPR/. (location: .)
    09-Mar-2020 10:07:02	Artifact 'code' prepared in 108.0 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE33-SEL4TUTORIALSGITLINTPR/./code.tar.gz
    09-Mar-2020 10:07:02	Running pre-build action: VCS Version Collector
    09-Mar-2020 10:07:02	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    09-Mar-2020 10:07:02	+ tar xf code.tar.gz --recursive-unlink
    09-Mar-2020 10:07:02	Finished task 'Untar code' with result: Success
    09-Mar-2020 10:07:02	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    09-Mar-2020 10:07:02	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE33-SEL4TUTORIALSGITLINTPR
    09-Mar-2020 10:07:02	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    09-Mar-2020 10:07:02	Starting task 'Lint commit messages' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    09-Mar-2020 10:07:02	+ cd seL4-tutorials
    09-Mar-2020 10:07:02	+ gitlint --commits master..7438f6111beea30736cdb69c814c34e764a33f0c --config /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE33-SEL4TUTORIALSGITLINTPR/seL4_tools/misc/.gitlint
    09-Mar-2020 10:07:06	3: B6 Body message is missing
    09-Mar-2020 10:07:06	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4TUTORIALSSTYLE33-SEL4TUTORIALSGITLINTPR-1-ScriptBuildTask-3565681133972219428.sh] was 1 while expected 0
    09-Mar-2020 10:07:06	Finished task 'Lint commit messages' with result: Failed
    09-Mar-2020 10:07:06	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    09-Mar-2020 10:07:06	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE33-SEL4TUTORIALSGITLINTPR
    09-Mar-2020 10:07:06	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    09-Mar-2020 10:07:06	Running post build plugin 'NCover Results Collector'
    09-Mar-2020 10:07:06	Running post build plugin 'Artifact Copier'
    09-Mar-2020 10:07:06	Running post build plugin 'npm Cache Cleanup'
    09-Mar-2020 10:07:06	Running post build plugin 'Clover Results Collector'
    09-Mar-2020 10:07:06	Running post build plugin 'Docker Container Cleanup'
    09-Mar-2020 10:07:06	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE33-SEL4TUTORIALSGITLINTPR'
    09-Mar-2020 10:07:06	Finalising the build...
    09-Mar-2020 10:07:06	Stopping timer.
    09-Mar-2020 10:07:06	Build CQ-SEL4TUTORIALSSTYLE33-SEL4TUTORIALSGITLINTPR-1 completed.
    09-Mar-2020 10:07:06	Running on server: post build plugin 'NCover Results Collector'
    09-Mar-2020 10:07:06	Running on server: post build plugin 'Build Hanging Detection Configuration'
    09-Mar-2020 10:07:06	Running on server: post build plugin 'Clover Delta Calculator'
    09-Mar-2020 10:07:06	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    09-Mar-2020 10:07:06	All post build plugins have finished
    09-Mar-2020 10:07:06	Generating build results summary...
    09-Mar-2020 10:07:06	Saving build results to disk...
    09-Mar-2020 10:07:06	Logging substituted variables...
    09-Mar-2020 10:07:06	Indexing build results...
    09-Mar-2020 10:07:06	Finished building CQ-SEL4TUTORIALSSTYLE33-SEL4TUTORIALSGITLINTPR-1.


This is the most I can report on right now, sorry!

**Comment by nomadeel** [comment]
@laokz Hey, I just wanted to follow-up on this PR. The reported errors indicate that the body message is missing from the commit. Could you fix this please? Or, if you're busy, would you be happy if I modified the commit so that it passes the style tests? I will also add you to the co-author of the commit.

**Comment by laokz** [comment]
My pleasure, please.

thks

**Comment by nomadeel** [comment]
Fixed up the commit and also rebased, going to pull this in.
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
