### PR TITLE
Fix typo in camkes tutorial hint.

### PR DESCRIPTION
**Pull request by Ben-PH**
want `<component>_wait()`, not `<component>.wait()` for the hint

### CODE REVIEW

**Comment by nomadeel** [comment]
Hey, thanks for the fix! I'll just run some style checks and then pull this in if they're good.

**Comment by nomadeel** [comment]
@ssrg-bamboo `test`

**Comment by nomadeel** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by nomadeel** [comment]
One last thing before I pull this change, is it possible if you could change the subject line so that it matches the imperative mood? I.e. comment typo -> Fix comment typo, or similar?

**Comment by Ben-PH** [comment]
Done.

**Comment by nomadeel** [comment]
Might be just me, but the subject line of the commit seems to not have been changed.

**Comment by Ben-PH** [comment]
Sorry, completely misread what you meant. I'll get onto that.

**Comment by Ben-PH** [comment]
Should that do it?

**Comment by nomadeel** [comment]
Perfect. Sorry if my explanation wasn't clear enough. I'll pull this patch in right now.

**Comment by Ben-PH** [comment]
all good. Thanks

**Pull request merged**
