### PR TITLE
hello-camkes-1: update md file to match code

### PR DESCRIPTION
**Pull request by Furao**
The Client and Echo components are actually defined in the hello-1.camkes file instead of their own .camkes files. This updates the instructions to match that.

### CODE REVIEW

**Comment by kent-mcleod** [comment]
@Furao thanks! @ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 203de16c0d2c464516ca0c290aaa4176e4106cee

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - seL4-tutorials - EXT-Furao-patch-1-31 | SUCCESSFUL |
| Code Quality - Style - seL4-tutorials - EXT-Furao-patch-1-31 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - seL4-tutorials - EXT-Furao-patch-1-31 | Style check on changed files | 1 of 3 jobs failed |

**Job: gitlint**
Build logs

    24-Oct-2019 10:02:17	Build Code Quality - Style - seL4-tutorials - EXT-Furao-patch-1-31 - gitlint #1 (CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR-1) started building on agent A local agent 2
    24-Oct-2019 10:02:17	I run on the Bamboo server!
    24-Oct-2019 10:02:17	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR
    24-Oct-2019 10:02:17	Executing build Code Quality - Style - seL4-tutorials - EXT-Furao-patch-1-31 - gitlint #1 (CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR-1)
    24-Oct-2019 10:02:17	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR/. (location: .)
    24-Oct-2019 10:02:17	Artifact 'code' prepared in 84.87 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR/./code.tar.gz
    24-Oct-2019 10:02:17	Running pre-build action: VCS Version Collector
    24-Oct-2019 10:02:17	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    24-Oct-2019 10:02:17	+ tar xf code.tar.gz --recursive-unlink
    24-Oct-2019 10:02:17	Finished task 'Untar code' with result: Success
    24-Oct-2019 10:02:17	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    24-Oct-2019 10:02:17	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR
    24-Oct-2019 10:02:17	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    24-Oct-2019 10:02:17	Starting task 'Lint commit messages' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    24-Oct-2019 10:02:17	+ cd seL4-tutorials
    24-Oct-2019 10:02:17	+ gitlint --commits master..203de16c0d2c464516ca0c290aaa4176e4106cee --config /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR/seL4_tools/misc/.gitlint
    24-Oct-2019 10:02:20	3: B1 Line exceeds max length (159>72): "The Client and Echo components are actually defined in the hello-1.camkes file instead of their own .camkes files. This updates the instructions to match that."
    24-Oct-2019 10:02:20	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR-1-ScriptBuildTask-3624072194892466819.sh] was 1 while expected 0
    24-Oct-2019 10:02:20	Finished task 'Lint commit messages' with result: Failed
    24-Oct-2019 10:02:20	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    24-Oct-2019 10:02:20	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR
    24-Oct-2019 10:02:20	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    24-Oct-2019 10:02:20	Running post build plugin 'NCover Results Collector'
    24-Oct-2019 10:02:20	Running post build plugin 'Artifact Copier'
    24-Oct-2019 10:02:20	Running post build plugin 'npm Cache Cleanup'
    24-Oct-2019 10:02:20	Running post build plugin 'Clover Results Collector'
    24-Oct-2019 10:02:20	Running post build plugin 'Docker Container Cleanup'
    24-Oct-2019 10:02:20	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR'
    24-Oct-2019 10:02:20	Finalising the build...
    24-Oct-2019 10:02:20	Stopping timer.
    24-Oct-2019 10:02:20	Build CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR-1 completed.
    24-Oct-2019 10:02:20	Running on server: post build plugin 'NCover Results Collector'
    24-Oct-2019 10:02:20	Running on server: post build plugin 'Build Hanging Detection Configuration'
    24-Oct-2019 10:02:20	Running on server: post build plugin 'Clover Delta Calculator'
    24-Oct-2019 10:02:20	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    24-Oct-2019 10:02:20	All post build plugins have finished
    24-Oct-2019 10:02:20	Generating build results summary...
    24-Oct-2019 10:02:20	Saving build results to disk...
    24-Oct-2019 10:02:20	Logging substituted variables...
    24-Oct-2019 10:02:20	Indexing build results...
    24-Oct-2019 10:02:20	Finished building CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR-1.


This is the most I can report on right now, sorry!

**Comment by ssrg-bamboo** [comment]
## Test results for commit cf26c67cc68dc668ddcc4a8b04944183517ec5eb

### Summary

#### NOTE: some test results have been updated!

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - seL4-tutorials - EXT-Furao-patch-1-31 | SUCCESSFUL |
| Code Quality - Style - seL4-tutorials - EXT-Furao-patch-1-31 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - seL4-tutorials - EXT-Furao-patch-1-31 | Style check on changed files | 1 of 3 jobs failed |

**Job: gitlint**
Build logs

    13-Nov-2019 16:18:09	Build Code Quality - Style - seL4-tutorials - EXT-Furao-patch-1-31 - gitlint #3 (CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR-3) started building on agent A local agent 1
    13-Nov-2019 16:18:09	I run on the Bamboo server!
    13-Nov-2019 16:18:09	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR
    13-Nov-2019 16:18:09	Executing build Code Quality - Style - seL4-tutorials - EXT-Furao-patch-1-31 - gitlint #3 (CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR-3)
    13-Nov-2019 16:18:09	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR/. (location: .)
    13-Nov-2019 16:18:09	Artifact 'code' prepared in 88.89 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR/./code.tar.gz
    13-Nov-2019 16:18:09	Running pre-build action: VCS Version Collector
    13-Nov-2019 16:18:09	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    13-Nov-2019 16:18:09	+ tar xf code.tar.gz --recursive-unlink
    13-Nov-2019 16:18:09	Finished task 'Untar code' with result: Success
    13-Nov-2019 16:18:09	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    13-Nov-2019 16:18:09	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR
    13-Nov-2019 16:18:09	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    13-Nov-2019 16:18:09	Starting task 'Lint commit messages' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    13-Nov-2019 16:18:09	+ cd seL4-tutorials
    13-Nov-2019 16:18:09	+ gitlint --commits master..cf26c67cc68dc668ddcc4a8b04944183517ec5eb --config /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR/seL4_tools/misc/.gitlint
    13-Nov-2019 16:18:15	
    13-Nov-2019 16:18:15	Commit cb5890cc45:
    13-Nov-2019 16:18:15	3: B1 Line exceeds max length (159>72): "The Client and Echo components are actually defined in the hello-1.camkes file instead of their own .camkes files. This updates the instructions to match that."
    13-Nov-2019 16:18:15	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR-3-ScriptBuildTask-1503496439564074909.sh] was 1 while expected 0
    13-Nov-2019 16:18:15	Finished task 'Lint commit messages' with result: Failed
    13-Nov-2019 16:18:15	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    13-Nov-2019 16:18:15	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR
    13-Nov-2019 16:18:15	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    13-Nov-2019 16:18:15	Running post build plugin 'NCover Results Collector'
    13-Nov-2019 16:18:15	Running post build plugin 'Artifact Copier'
    13-Nov-2019 16:18:15	Running post build plugin 'npm Cache Cleanup'
    13-Nov-2019 16:18:15	Running post build plugin 'Clover Results Collector'
    13-Nov-2019 16:18:15	Running post build plugin 'Docker Container Cleanup'
    13-Nov-2019 16:18:15	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR'
    13-Nov-2019 16:18:15	Finalising the build...
    13-Nov-2019 16:18:15	Stopping timer.
    13-Nov-2019 16:18:15	Build CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR-3 completed.
    13-Nov-2019 16:18:15	Running on server: post build plugin 'NCover Results Collector'
    13-Nov-2019 16:18:15	Running on server: post build plugin 'Build Hanging Detection Configuration'
    13-Nov-2019 16:18:15	Running on server: post build plugin 'Clover Delta Calculator'
    13-Nov-2019 16:18:15	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    13-Nov-2019 16:18:15	All post build plugins have finished
    13-Nov-2019 16:18:15	Generating build results summary...
    13-Nov-2019 16:18:15	Saving build results to disk...
    13-Nov-2019 16:18:15	Logging substituted variables...
    13-Nov-2019 16:18:15	Indexing build results...
    13-Nov-2019 16:18:15	Finished building CQ-SEL4TUTORIALSSTYLE18-SEL4TUTORIALSGITLINTPR-3.


This is the most I can report on right now, sorry!

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by kent-mcleod** [comment]
Merged in f8e317a2f0fd55aaa6535afb07c86bdfb728310c

**Pull request closed without merging**
