### PR TITLE
Fix initial output doc for notifications tute

### PR DESCRIPTION
**Pull request by maybe-sybr**
We don't expect to see a fault because neither of the producers will
touch their as yet unshared frame until woken from their `Wait()` call.

### CODE REVIEW

**Comment by maybe-sybr** [comment]
Alternatively we could make the fault happen, I suppose. Zeroing the word at the top of one or both of the producers' `buf` as "initialisation" seems believable.

**Comment by kent-mcleod** [comment]
Thanks! @ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
