### PR TITLE
Correct CNode size from bytes to slots

### LINKED ISSUE #47: Mistake in capabilities tutorial
Not sure if this is the correct place to post this.

Lines 162-163 of [capabilities.md](https://github.com/SEL4PROJ/sel4-tutorials/blob/master/tutorials/capabilities/capabilities.md), which are lines 4-5 of the main.c file:
```c
size_t initial_cnode_object_size = BIT(info->initThreadCNodeSizeBits);
printf("Initial CNode is %zu bytes in size\n", initial_cnode_object_size);
```
However, `BIT(n)` is `1ul<<n`, so this is not in fact reporting the CNode size is bytes.

If I understand correctly, `BIT(info->initThreadCNodeSizeBits)` would be the number of `CSlots` the `CNode` can hold, so the `printf` should perhaps read:
```c
printf("Initial CNode is %zu slots in size\n", initial_cnode_object_size);
```

Of course this is inconsequential to what the tutorial is teaching, but it seemed worth pointing out.

### PR DESCRIPTION
**Pull request by lainy**
Fixes #47

### CODE REVIEW

**Comment by walle-whale** [comment]
@ssrg-bamboo `test`

**Comment by walle-whale** [comment]
Thanks!

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by lainy** [comment]
Whoops, just realized there were a couple other places that refer to 'bytes' instead of 'slots'.
Fixed with the latest commit.

**Comment by lainy** [comment]
Please forgive my ignorance as I learn seL4. You can probably close this PR and the associated issue, I believe I have misunderstood how this all works.

The tutorial states:
>CSlots are `1u << seL4_SlotBits` in size, and as a result the number of slots in a CNode can be calculated by `CNodeSize / (1u << seL4_SlotBits)`.

Looking at the source, for example https://github.com/seL4/seL4/blob/master/include/object/structures.h#L400, it looks like the original wording is actually correct: `1u << seL4_SlotBits` is the number of _bytes_ a CSlot occupies.

It seems like in general the `Bits` suffix indicates you are expected to take `2^Bits` to calculate the size in bytes. Is that correct?

**Comment by walle-whale** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by walle-whale** [comment]
Yes, that's correct. We should create an issue to make these things clearer.

**Comment by xurtis** [comment]
I don't see why this was closed, table 9.2 of the manual and the source code agree with your initial conclusion, `initThreadCNodeSizeBits` in the bootinfo structure describes the log2 of the number of *slots* in the initial CNode, not the number of bytes. CNodes are always configured [in terms of the number of slots](https://github.com/seL4/seL4/blob/master/src/object/objecttype.c#L46).

The use of the `Bits` suffix is used to refer to numbers encoded as the log2 of their value rather than the value itself, but this is used in many different contexts. For raw object sizes within the kernel, this is the size in bytes. The values in the `seL4_BootInfo` and the values passed as an argument to `seL4_Untyped_Retype` depend on the object being created.

**Pull request closed without merging**
